#!/usr/bin/env python3
"""
Modern Flight Tracker Dashboard - Flask app on localhost:3737
Shows top 5 flights with details, trends, price alerts, Amex points analysis
Reads from JSON data files generated by cron jobs
"""
from flask import Flask, jsonify, send_from_directory
import json
import os
from datetime import datetime, timedelta
import re

BASE_PATH = "/Users/gerald/.openclaw/workspace/flight-tracker"
TEMPLATE_PATH = os.path.join(BASE_PATH, "templates")
DATA_PATH = os.path.join(BASE_PATH, "data")
HISTORY_FILE = os.path.join(DATA_PATH, "history.jsonl")

app = Flask(__name__)

def get_latest_flight_data():
    """Get the most recent flight data from JSON files"""
    # Find latest date file in data/
    latest_file = None
    latest_date = None
    
    if os.path.exists(DATA_PATH):
        for fname in os.listdir(DATA_PATH):
            if fname.endswith('.json') and fname != 'history.jsonl':
                try:
                    # Extract date from filename (YYYY-MM-DD.json)
                    date_str = fname.replace('.json', '')
                    if re.match(r'\d{4}-\d{2}-\d{2}', date_str):
                        if latest_date is None or date_str > latest_date:
                            latest_date = date_str
                            latest_file = os.path.join(DATA_PATH, fname)
                except:
                    pass
    
    if latest_file and os.path.exists(latest_file):
        with open(latest_file) as f:
            return json.load(f)
    return None

def get_flight_history(airline_name):
    """Get price history for flights containing a specific airline"""
    if not os.path.exists(DATA_PATH):
        return []
    
    history = {}  # Use dict to avoid duplicates per day
    
    # Scan all date files
    for fname in sorted(os.listdir(DATA_PATH)):
        if fname.endswith('.json') and re.match(r'\d{4}-\d{2}-\d{2}', fname.replace('.json', '')):
            try:
                file_path = os.path.join(DATA_PATH, fname)
                with open(file_path) as f:
                    data = json.load(f)
                
                timestamp = data.get('timestamp', '')
                flights = data.get('flights', [])
                date_str = datetime.fromisoformat(timestamp.replace('Z', '+00:00')).strftime('%Y-%m-%d')
                
                # Search for the airline in the flights array
                for flight in flights:
                    flight_airline = flight.get('airline', '')
                    price_val = flight.get('price', 0)
                    
                    # Check if airline name is in the flight airline string (case-insensitive)
                    if airline_name.lower() in flight_airline.lower():
                        try:
                            # Handle both integer and string price formats
                            if isinstance(price_val, str):
                                # Parse string like "$2,532" to integer
                                price = int(price_val.replace('$', '').replace(',', ''))
                            else:
                                # Already an integer
                                price = int(price_val)
                            
                            # Store the first matching flight for this date
                            # (they're sorted by price, so first match is cheapest)
                            if date_str not in history:
                                history[date_str] = {
                                    'date': date_str,
                                    'price': price,
                                    'timestamp': timestamp
                                }
                            break
                        except Exception as parse_err:
                            pass
            except Exception as e:
                pass
    
    return list(history.values())

def get_flight_data():
    """Get flights from tracker output"""
    data = get_latest_flight_data()
    
    if not data:
        return []
    
    flights_data = data.get('flights', [])
    
    if not flights_data:
        return []
    
    # Deduplicate: keep only first occurrence of each unique flight
    # (same airline, departure, arrival)
    seen = {}
    unique_flights = []
    for flight in flights_data:
        key = (flight.get('airline', ''), flight.get('departure', ''), flight.get('arrival', ''))
        if key not in seen:
            seen[key] = True
            unique_flights.append(flight)
    
    # Convert to frontend format
    flights = []
    for flight in unique_flights[:15]:  # Top 15 UNIQUE flights
        # Get layover info - already formatted from amadeus as "duration in CITY"
        layover_str = flight.get('layover', '')
        
        # Use layover string as-is (already properly formatted from data collection)
        # e.g., "1h 45m in MUC" or "2h 30m in ORD"
        layover_display = layover_str if layover_str else flight.get('stops', '1 stop')
        
        # Extract just the duration part (before "in")
        layover_duration = flight.get('layover_time', '')
        if not layover_duration and layover_str:
            # Fall back to parsing from full string
            parts = layover_str.split(' in ')
            layover_duration = parts[0] if parts else ''
        
        # Parse price
        price_val = flight.get('price', 0)
        if isinstance(price_val, str):
            price_per_person = int(price_val.replace('$', '').replace(',', ''))
        else:
            price_per_person = int(price_val)
        
        price_round_trip = price_per_person * 2
        
        # Create booking link - prioritize Amadeus for exact matches, fallback to Google Flights
        booking_url = flight.get('booking_url', '')
        
        if not booking_url or 'amadeus.com' not in booking_url:
            # Google Flights direct link (without pre-filters, since Google doesn't support them well)
            # Format: /travel/flights/?q=SAN-ATH,2026-06-12~ATH-SAN,2026-06-22,2,e
            booking_url = (
                "https://www.google.com/travel/flights?"
                "q=SAN-ATH,2026-06-12~ATH-SAN,2026-06-22,2,e"
            )
        
        formatted = {
            'airline': flight.get('airline', ''),
            'departure': flight.get('departure', ''),
            'arrival': flight.get('arrival', ''),
            'duration': flight.get('duration', ''),
            'stops': flight.get('stops', '1 stop'),
            'layover': layover_display,
            'layover_time': layover_duration,
            'price_per_person': f"${price_per_person:,}",
            'price_round_trip': f"${price_round_trip:,}",
            'price': price_per_person,  # Return per-person price as integer for validation
            'booking_url': booking_url,
            'amadeus_id': flight.get('amadeus_id', ''),
            'source': flight.get('source', 'unknown')
        }
        flights.append(formatted)
    
    return flights

def get_flight_history_for_airline(airline_name):
    """Get historical prices for a specific airline"""
    history = {}
    
    if not os.path.exists(DATA_PATH):
        return []
    
    # Scan all date files
    for fname in sorted(os.listdir(DATA_PATH)):
        if fname.endswith('.json') and re.match(r'\d{4}-\d{2}-\d{2}', fname.replace('.json', '')):
            try:
                file_path = os.path.join(DATA_PATH, fname)
                with open(file_path) as f:
                    data = json.load(f)
                
                timestamp = data.get('timestamp', '')
                flights = data.get('flights', [])
                date_str = fname.replace('.json', '')
                
                # Search for the airline in the flights array
                for flight in flights:
                    flight_airline = flight.get('airline', '')
                    
                    # Check if airline name matches (case-insensitive)
                    if airline_name.lower() in flight_airline.lower():
                        try:
                            price_str = str(flight.get('price', '')).replace('$', '').replace(',', '')
                            price = float(price_str)
                            
                            # Store the first matching flight for this date
                            if date_str not in history:
                                history[date_str] = price
                            break
                        except:
                            pass
            except:
                pass
    
    return list(history.values())

def get_top_10_flights():
    """Get top 15 flights from real scraped data with historical pricing"""
    flights = get_flight_data()[:15]  # Get top 15
    
    # Enrich each flight with historical data
    for flight in flights:
        airline = flight.get('airline', '')
        # Handle both int and string price formats
        price_val = flight.get('price', 0)
        if isinstance(price_val, str):
            current_price_str = price_val.replace('$', '').replace(',', '')
            try:
                current_price = float(current_price_str)
            except:
                current_price = 0
        else:
            current_price = float(price_val)
        
        # Get historical prices for this airline
        hist_prices = get_flight_history_for_airline(airline)
        
        if hist_prices:
            avg_price = sum(hist_prices) / len(hist_prices)
            pct_change = ((current_price - avg_price) / avg_price * 100) if avg_price > 0 else 0
            
            flight['avg_historical_price'] = f"${avg_price:.0f}"
            flight['pct_change'] = f"{pct_change:+.1f}%"
            flight['price_color'] = "green" if pct_change < 0 else "red"
        else:
            flight['avg_historical_price'] = "N/A"
            flight['pct_change'] = "N/A"
            flight['price_color'] = "gray"
    
    return flights

def get_top_5_flights():
    """Legacy: Get top 5 flights (use get_top_10_flights for full data)"""
    return get_top_10_flights()[:5]

def get_price_trends():
    """Get price trends from daily JSON files (last 7 days)"""
    trends = []
    
    if not os.path.exists(DATA_PATH):
        return []
    
    try:
        # Scan all date files in data directory
        for fname in sorted(os.listdir(DATA_PATH)):
            if fname.endswith('.json') and re.match(r'\d{4}-\d{2}-\d{2}', fname.replace('.json', '')):
                file_path = os.path.join(DATA_PATH, fname)
                with open(file_path) as f:
                    data = json.load(f)
                    
                timestamp = data.get('timestamp', '')
                stats = data.get('stats', {})
                
                # If file doesn't have stats, calculate from flights
                if not stats or not stats.get('min'):
                    flights = data.get('flights', [])
                    prices = []
                    for flight in flights:
                        try:
                            # Try to get price - handle both price and raw_price_per_person fields
                            price = flight.get('price')
                            if not price:
                                price = flight.get('raw_price_per_person')
                            
                            if isinstance(price, str):
                                price = int(price.replace('$', '').replace(',', ''))
                            elif isinstance(price, (int, float)):
                                price = int(price)
                            
                            if price and price > 0:
                                prices.append(price)
                        except:
                            pass
                    
                    if prices:
                        # Detect if prices are per-person or round-trip
                        # Round-trip prices are typically 1.5x-2x per-person for same airlines
                        # If min > 2000, likely already round-trip (should be normalized to per-person)
                        avg_price = sum(prices) / len(prices)
                        is_round_trip = avg_price > 1500  # Heuristic: round-trip prices > $1500
                        
                        if is_round_trip:
                            # Divide by 2 to get per-person
                            prices = [p / 2 for p in prices]
                        
                        stats = {
                            'min': min(prices),
                            'max': max(prices),
                            'avg': sum(prices) / len(prices),
                            'count': len(prices)
                        }
                
                # Parse timestamp to get date
                try:
                    dt = datetime.fromisoformat(timestamp.replace('Z', '+00:00'))
                    date_str = dt.strftime('%Y-%m-%d')
                except:
                    date_str = fname.replace('.json', '')
                
                # Store both min (for 2 passengers) and per-person for consistency
                trends.append({
                    "date": date_str,
                    "best_price": stats.get('min'),
                    "average_price": stats.get('avg'),
                    "max_price": stats.get('max'),
                    "count": stats.get('count', 0)
                })
    except Exception as e:
        print(f"Error reading trends: {e}")
    
    # Keep only unique dates, using the latest entry per date
    seen = {}
    for t in reversed(trends):
        if t['date'] not in seen:
            seen[t['date']] = t
    
    return list(reversed(list(seen.values())))  # All available data (no limit)

def get_price_alerts():
    """Get recent price alerts from alerts log"""
    alerts_file = os.path.join(BASE_PATH, "alerts", "price-drops.log")
    alerts = []
    
    if os.path.exists(alerts_file):
        try:
            with open(alerts_file) as f:
                for line in f.readlines()[-5:]:  # Last 5 alerts
                    if line.strip():
                        # Parse log format: timestamp | DROP: -$X (-Y%) | was → now
                        parts = line.split('|')
                        if len(parts) >= 2:
                            alerts.append({
                                "timestamp": parts[0].strip(),
                                "alert": parts[1].strip() if len(parts) > 1 else "Price drop detected"
                            })
        except:
            pass
    
    return alerts

def amex_optimizer():
    """Calculate best Amex points usage"""
    points_available = 250000
    points_per_usd = 0.02  # 2 cents per point
    usd_value = points_available * points_per_usd
    
    # Suggested redemptions
    suggestions = [
        {
            "program": "Lufthansa Miles & More",
            "miles_needed": 120000,  # Round trip SAN-ATH economy
            "estimated_value": "$2400",
            "efficiency": "2 cpp"
        },
        {
            "program": "Air Canada Aeroplan",
            "miles_needed": 110000,
            "estimated_value": "$2200",
            "efficiency": "2 cpp"
        },
        {
            "program": "BA Avios",
            "miles_needed": 100000,
            "estimated_value": "$2000",
            "efficiency": "2 cpp"
        }
    ]
    
    return {
        "total_points": points_available,
        "estimated_cash_value": f"${usd_value:.0f}",
        "suggestions": suggestions
    }

@app.route('/')
def dashboard_page():
    """Serve the HTML dashboard"""
    return send_from_directory(TEMPLATE_PATH, 'index.html')

@app.route('/api/dashboard')
def dashboard():
    """API endpoint - returns JSON data for the frontend"""
    latest_data = get_latest_flight_data()
    
    data = {
        "trip": {
            "from": "San Diego (SAN)",
            "to": "Athens (ATH)",
            "depart": "June 12, 2026",
            "return": "June 22, 2026",
            "passengers": 2
        },
        "top_5_flights": get_top_5_flights(),
        "price_trends": get_price_trends(),
        "recent_alerts": get_price_alerts(),
        "amex_insights": amex_optimizer(),
        "latest_stats": latest_data.get('stats') if latest_data else None,
        "last_checked": latest_data.get('timestamp') if latest_data else datetime.now().isoformat()
    }
    
    return jsonify(data)

@app.route('/api/flights')
def flights():
    """Get top 10 flights"""
    return jsonify({
        "flights": get_top_10_flights(),
        "timestamp": datetime.now().isoformat()
    })

@app.route('/api/real-prices')
def real_prices():
    """Get real booking prices from all platforms"""
    try:
        import subprocess
        import json
        
        result = subprocess.run(
            ["python3", os.path.join(BASE_PATH, "price-scraper.py")],
            capture_output=True,
            text=True,
            timeout=120
        )
        
        # Extract JSON from output (find first { and last })
        output = result.stdout
        start = output.find('{')
        end = output.rfind('}') + 1
        
        if start >= 0 and end > start:
            json_str = output[start:end]
            prices = json.loads(json_str)
            return jsonify(prices)
        else:
            raise ValueError("No JSON found in output")
    
    except Exception as e:
        return jsonify({
            "error": str(e),
            "message": "Could not fetch real prices"
        }), 500

@app.route('/api/flight-history/<airline>')
def flight_history(airline):
    """Get price history for a specific airline"""
    history = get_flight_history(airline)
    return jsonify({
        "airline": airline,
        "history": history
    })

@app.route('/api/data')
def api_data():
    """API endpoint for the new dashboard"""
    latest_data = get_latest_flight_data()
    trends = get_price_trends()
    flights = get_top_10_flights()
    
    # Calculate stats from latest flight data
    latest_stats = {}
    if latest_data and latest_data.get('flights'):
        flight_prices = []
        for f in latest_data.get('flights', []):
            try:
                price = f.get('price', 0)
                if isinstance(price, str):
                    price = int(price.replace('$', '').replace(',', ''))
                if price > 0:
                    flight_prices.append(price)
            except:
                pass
        
        if flight_prices:
            latest_stats = {
                "min": min(flight_prices),
                "max": max(flight_prices),
                "avg": sum(flight_prices) / len(flight_prices),
                "count": len(flight_prices)
            }
    
    history = []
    for trend in trends:
        history.append({
            "timestamp": trend.get('date'),
            "stats": {
                "min": trend.get('best_price'),
                "avg": trend.get('average_price'),
                "max": trend.get('max_price'),
                "count": trend.get('count', 0)
            }
        })
    
    return jsonify({
        "latest": {
            "timestamp": latest_data.get('timestamp') if latest_data else datetime.now().isoformat(),
            "stats": latest_stats
        },
        "history": history,
        "flights": flights
    })

@app.route('/health')
def health():
    """Health check endpoint"""
    latest_data = get_latest_flight_data()
    return jsonify({
        "status": "ok",
        "service": "flight-tracker",
        "timestamp": datetime.now().isoformat(),
        "data_available": latest_data is not None
    })

if __name__ == '__main__':
    app.run(debug=True, port=3737, host='localhost')
